version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '10:00'
      timezone: 'America/Sao_Paulo'
    target-branch: 'main'
    groups:
      dependencies:
        applies-to: 'version-updates'
        update-types:
          - 'minor'
          - 'patch'
